#!/bin/bash

source ~/.bashrc
iter=2
#module load python/2.7.15

if [[ "$1" == *"createmodule"* ]]
then
module load intel
f2py -c \
*.f90 \
-m fort_analysis \
--opt='-O3 -fopenmp' --fcompiler=intelem --f90flags='-fopenmp -g -traceback' --compiler=unix -DF2PY_REPORT_ATEXIT
echo "module created"
fi


